language: rust
rust: nightly
install: cargo build
cache: cargo
jobs:
  include:
    - script: cargo test
    - script: cargo test --features sqlite
    - script:
      - cd eva-cli
      - cargo test
