[package]
name = "eva-cli"
version = "0.0.1"
authors = ["Stijn Seghers <stijnseghers@gmail.com>"]
edition = "2018"

[dependencies]
app_dirs = "1.1"
chrono = "0.4"
clap = "2.26"
config = "0.9"
eva = { version = "0.0.1", path = "../", features = ["sqlite"] }
failure = "0.1"
futures-preview = "0.3.0-alpha.12"
itertools = "0.7"
shellexpand = "1.0"
