[package]
name = "eva-cli"
version = "0.0.1"
authors = ["Stijn Seghers <stijnseghers@gmail.com>"]

[dependencies]
app_dirs = "1.1"
chrono = "0.4"
clap = "2.26"
config = "0.8"
error-chain = "0.11"
eva = { version = "0.0.1", path = "../" }
shellexpand = "1.0"
